### Load Transcriptomics proteomics dataset

In [3]:
import numpy as np
import pandas as pd
#import networkx as nx
import sys, os, h5py
sys.path.append(os.path.abspath('/home/samuele/EMOGI/EMOGI'))
sys.path.append(os.path.abspath('/home/samuele/GhostFreePro/data_preprocessing_pipeline/'))
import gcnPreprocessing
import gcnIO
import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures
from torch_geometric.data.data import Data 

/home/samuele/mambaforge/envs/pytorch_geometric/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [13]:
data = gcnIO.load_hdf_data('/home/samuele/GhostFreePro/data_preprocessing_pipeline/artivir_data/containers/transcriptomics-proteomics-effectome_2022_9_13_17_42_non_zero_imputed_values.h5')

In [14]:
network, features, y_train, y_val, y_test, train_mask, val_mask, test_mask, node_names, feat_names = data

In [6]:
partial_features = features[0:2]
partial_features

array([[ 0.07098466, -0.10048157, -0.06661676, -0.09941968,  0.37677982,
         0.08926854,  0.72849319, -0.57474649,  1.38637147,  1.15450585,
         0.11099949, -0.11165193,  0.26573501,  0.05721614, -0.09206121,
        -0.21766928,  0.01533022,  1.59906327,  0.58322577, -0.1524168 ,
         0.26235958, -0.29256413, -0.16970129,  0.20686008, -0.33622227,
         0.65523949],
       [ 1.17359033,  0.03416442, -0.17131518,  0.0066981 , -0.17422146,
         0.25212816,  0.33225033,  0.03114607,  0.40217749,  0.39166725,
         0.45350497,  0.20819322,  0.88539186, -0.15137955,  0.34366951,
         0.11229018, -0.15766404, -0.19172691,  0.13194933,  0.33248612,
         0.01893305, -0.40965704,  0.0964637 , -0.08570543, -0.55707282,
        -0.42858111]])

In [19]:
tra = features[0:2][:, 0]
tra

array([0.07098466, 1.17359033])

In [45]:
pro = features[0:2][:, 1]
pro

array([-0.10048157,  0.03416442])

In [42]:
eff = features[0:2][:, 2:26]
eff

array([[-0.06661676, -0.09941968,  0.37677982,  0.08926854,  0.72849319,
        -0.57474649,  1.38637147,  1.15450585,  0.11099949, -0.11165193,
         0.26573501,  0.05721614, -0.09206121, -0.21766928,  0.01533022,
         1.59906327,  0.58322577, -0.1524168 ,  0.26235958, -0.29256413,
        -0.16970129,  0.20686008, -0.33622227,  0.65523949],
       [-0.17131518,  0.0066981 , -0.17422146,  0.25212816,  0.33225033,
         0.03114607,  0.40217749,  0.39166725,  0.45350497,  0.20819322,
         0.88539186, -0.15137955,  0.34366951,  0.11229018, -0.15766404,
        -0.19172691,  0.13194933,  0.33248612,  0.01893305, -0.40965704,
         0.0964637 , -0.08570543, -0.55707282, -0.42858111]])

In [48]:
partial_features == np.concatenate((np.transpose([tra]), np.transpose([pro]), eff), axis=1)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]])

In [30]:
eff

array([[-0.06661676, -0.09941968,  0.37677982,  0.08926854,  0.72849319,
        -0.57474649,  1.38637147,  1.15450585,  0.11099949, -0.11165193,
         0.26573501,  0.05721614, -0.09206121, -0.21766928,  0.01533022,
         1.59906327,  0.58322577, -0.1524168 ,  0.26235958, -0.29256413,
        -0.16970129,  0.20686008, -0.33622227],
       [-0.17131518,  0.0066981 , -0.17422146,  0.25212816,  0.33225033,
         0.03114607,  0.40217749,  0.39166725,  0.45350497,  0.20819322,
         0.88539186, -0.15137955,  0.34366951,  0.11229018, -0.15766404,
        -0.19172691,  0.13194933,  0.33248612,  0.01893305, -0.40965704,
         0.0964637 , -0.08570543, -0.55707282]])

In [7]:
np.shape(features)

(13594, 26)

In [9]:
len(features)

13594

In [18]:
np.shape(np.identity(len(features)))

(13594, 13594)

In [20]:
np.identity(len(features)).shape

(13594, 13594)

In [16]:
features.shape

(13594, 26)

### Load torch sample dataset

In [4]:
from feature_preselection_transcriptome_proteome import create_trivial_features

In [5]:
dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
data = dataset[0]

In [6]:
data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [7]:
len(data.edge_index[0])

10556

In [8]:
np.shape(network)
print(f'num edges {np.sum(network != 0)}')

num edges 510036


### Create emogi data torch tensor

In [9]:
emogi_data = Data()
emogi_data.edge_index = torch.Tensor(np.where(network[:,:] != 0)).long()
emogi_data.x = torch.tensor(features).float()
emogi_data.y = torch.tensor(y_val.transpose()[0] + y_test.transpose()[0] + y_train.transpose()[0]).long()
emogi_data.train_mask = torch.tensor(train_mask).bool()
emogi_data.test_mask = torch.tensor(test_mask).bool()
emogi_data.val_mask = torch.tensor(val_mask).bool()

/tmp/ipykernel_68678/234338472.py:2: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:204.)
  emogi_data.edge_index = torch.Tensor(np.where(network[:,:] != 0)).long()


In [10]:
emogi_data.x[3]

tensor([-0.1735,  0.0964])

In [11]:
torch.Tensor(np.where(network[:,:] != 0)).long()

tensor([[   0,    0,    0,  ..., 5540, 5540, 5540],
        [  64,  196,  232,  ..., 5384, 5444, 5522]])

In [12]:
torch.ones((emogi_data.edge_index.size(1), ), dtype=None, device=emogi_data.edge_index.device)

tensor([1., 1., 1.,  ..., 1., 1., 1.])

In [13]:
torch.Tensor(network[np.where(network[:,:] != 0)])

tensor([0.2718, 0.2738, 0.2728,  ..., 0.2417, 0.2006, 0.1795])

In [14]:
emogi_data.x

tensor([[ 1.3181,  0.2423],
        [ 0.0325, -0.8612],
        [-0.3606, -0.6360],
        ...,
        [ 0.2723, -0.2496],
        [ 0.2053, -0.1626],
        [-0.9576, -0.0987]])

In [15]:
data.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [37]:
y_tmp = emogi_data.y + np.arange(len(emogi_data.y))
y_tmp = torch.reshape(y_tmp, [len(y_tmp), 1])
y_tmp.size()

torch.Size([5541, 1])

In [46]:
#torch.reshape(y_tmp, [len(y_tmp)])
y_tmp.t()[0].size()

torch.Size([5541])

### Check positive trining test and validation sets

In [16]:
print(np.sum(y_train[np.where(y_val !=0)[0]]))
print(np.sum(y_val[np.where(y_train !=0)[0]]))
print(np.sum(y_train[np.where(y_test !=0)[0]]))
print(np.sum(y_test[np.where(y_train !=0)[0]]))
print(np.sum(y_test[np.where(y_val !=0)[0]]))
print(np.sum(y_val[np.where(y_test !=0)[0]]))
print(len(np.where(y_val !=0)[0]) + len(np.where(y_test !=0)[0]) + len(np.where(y_train !=0)[0]))

0.0
0.0
0.0
0.0
0.0
0.0
317


### Check train, test and validation sets

In [62]:
print(np.sum(train_mask[np.where(val_mask !=0)[0]]))
print(np.sum(val_mask[np.where(train_mask !=0)[0]]))
print(np.sum(train_mask[np.where(test_mask !=0)[0]]))
print(np.sum(test_mask[np.where(train_mask !=0)[0]]))
print(np.sum(test_mask[np.where(val_mask !=0)[0]]))
print(np.sum(val_mask[np.where(test_mask !=0)[0]]))
print(len(np.where(val_mask !=0)[0]) + len(np.where(test_mask !=0)[0]) + len(np.where(train_mask !=0)[0]))

0.0
0.0
0.0
0.0
0.0
0.0
1268


In [63]:
def cal_weights_model_torch_dataset(dataset):
	labels = []
	for data in dataset:
		labels += data.y.tolist()
	labels_tensor = torch.tensor(labels).squeeze()
	n_positive = labels_tensor.nonzero().size(0)
	n_negative = labels_tensor.size(0) - n_positive
	n_full = labels_tensor.size(0)
	return torch.tensor([n_full / (2 * n_negative), n_full / (2 * n_positive)])

In [64]:
def cal_weights_model(tensor_data):
	n_positive = tensor_data.y.sum()
	n_negative = tensor_data.train_mask.sum() + tensor_data.val_mask.sum() + tensor_data.test_mask.sum() - tensor_data.y.sum()
	n_full = tensor_data.train_mask.sum() + tensor_data.val_mask.sum() + tensor_data.test_mask.sum()
	return torch.tensor([n_full / (2 * n_negative), n_full / (2 * n_positive)])

In [65]:
diziomario = {"cane":10, "gatto":20}

In [66]:
len(diziomario)

2

In [70]:
mask_all = np.logical_or(emogi_data.train_mask, emogi_data.val_mask)
mask_all

tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [72]:
mask_all.sum() == emogi_data.train_mask.sum() + emogi_data.val_mask.sum()

tensor(True)

In [ ]:
y_all = np.logical_end(emogi_data.y, y_val)

In [167]:
def k_fold_test(lista, folds):
    #mock data
    y = (lista % 4 == 0).astype(int)
    mask = np.zeros_like(lista)
    mask[np.where((lista % 2) == 0)[0]] = 1
    
    skf = StratifiedKFold(folds, shuffle=True, random_state=12345)
    label_idx = np.where(mask == 1)[0] # get indices of labeled genes
    skf = StratifiedKFold(n_splits=folds, shuffle=True)
    splits = skf.split(label_idx, y[label_idx])   
    
    k_sets = []
    for train, test in splits:
        train_idx = label_idx[train]
        test_idx = label_idx[test]
        train_mask = np.zeros_like(mask)
        train_mask[train_idx] = 1
        test_mask = np.zeros_like(mask)
        test_mask[test_idx] = 1
        k_sets.append((train_mask, test_mask))
         
    
    return k_sets, y, mask

In [200]:
emogi_data

Data(edge_index=[2, 510036], x=[5541, 2], y=[5541], train_mask=[5541], test_mask=[5541], val_mask=[5541])

In [217]:
sum(emogi_data.train_mask + emogi_data.val_mask)

tensor(952)

In [220]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [215]:
torch.tensor([0,0,1,1], dtype=torch.bool) + torch.tensor([1,1,0,0], dtype=torch.bool)

tensor([True, True, True, True])

In [207]:
sum(emogi_data.val_mask)

tensor(128)

In [107]:
lista = np.arange(100)

In [192]:
k_sets, y, mask = k_fold_test(lista, 5)

In [193]:
k_sets[0][1] + k_sets[1][1] + k_sets[2][1]

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [199]:
k_sets[0][1] + k_sets[1][1] + k_sets[2][1] + k_sets[3][1] + k_sets[4][1] 

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [177]:
k_sets[0][0] + k_sets[1][0] + k_sets[2][0]

array([2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0])

In [191]:
sum(y[k_sets[0][1] == 1])

9

In [187]:
sum(k_sets[0][1]) + sum(k_sets[0][0])

50

In [182]:
y

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [221]:
#!/usr/bin/env python
import psutil
# gives a single float value
psutil.cpu_percent()
# gives an object with many fields
psutil.virtual_memory()
# you can convert that object to a dictionary 
dict(psutil.virtual_memory()._asdict())
# you can have the percentage of used RAM
psutil.virtual_memory().percent
# you can calculate percentage of available memory
psutil.virtual_memory().available * 100 / psutil.virtual_memory().total

28.265382589016657

In [253]:
psutil.cpu_percent()

50.4

In [255]:
psutil.virtual_memory().percent

84.9